---
- name: 'Create consul directory'
  file:
    path: '/etc/consul'
    owner: 'root'
    group: 'consul'
    mode: 0755
    state: directory

- name: 'Generate service config'
  template:
    dest: '/etc/consul/{{ consul_config_file }}'
    src: 'service.json.j2'
    owner: 'root'
    group: 'consul'
    mode: 0644
  register: consul_config

- name: 'Validate JSON syntax'
  command: 'jq . "/etc/consul/{{ consul_config_file }}"'
  environment:
    PATH: '/opt/homebrew/bin:/usr/local/bin'
  changed_when: false

- name: Restart consul
  community.general.launchd:
    name: 'io.consul'
    state: 'restarted'
  when: consul_config.changed
