---
- name: 'Create consul directory'
  file:
    path: '/etc/consul'
    owner: root
    group: adm
    mode: 0755
    state: directory

- name: 'Generate service config'
  template:
    dest: '/etc/consul/{{ consul_config_file }}'
    src: 'service.json.j2'
    trim_blocks: false
    owner: 'root'
    group: 'consul'
    mode: 0640
  register: consul_config

- name: 'Validate JSON syntax'
  command: 'jq . "/etc/consul/{{ consul_config_file }}"'
  changed_when: false

- name: Reload consul
  service:
    name: 'consul'
    state: 'reloaded'
  when: consul_config.changed
