---
- name: "Create consul directories"
  file:
    path: "{{ item }}"
    owner: root
    group: adm
    mode: 0755
    state: directory
  with_items:
    - "{{ consul_config_path }}"
  tags: ['consul-service']

- name: "Configure consul"
  template:
    dest: "{{ consul_config_path }}/service_{{ consul_service_name }}.json"
    src: service.json.j2
    owner: root
    group: adm
    mode: 0644
  when: consul_service_name is defined
  notify: "Reload consul"
  tags: ['consul-service', 'files']
