---
- name: 'Create consul directories'
  file:
    path: '{{ consul_config_path }}'
    owner: root
    group: adm
    mode: 0755
    state: directory
  loop_control:
    loop_var: file_path

- name: 'Configure consul'
  template:
    dest: '{{ consul_config_path }}/service_{{ consul_config_name | replace("-", "_") }}.json'
    src: service.json.j2
    owner: root
    group: adm
    mode: 0644
  when: consul_config_name is defined
  notify: 'Reload consul'

- name: 'Check JSON config syntax'
  shell: 'cat "{{ consul_config_path }}/service_{{ consul_config_name | replace("-", "_") }}.json" | jq .'
